# api lists

### create new client profile

POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "fname":"spidey",
    "lname": "doom",
    "email":"email@iii.co",
    "password":"1234Aa/",
    "phone":"999999999",
    "dob": "1993-04-23",
    "address":"11 sydney St",
    "gender":"male"

}


### email verification API

POST http://localhost:8000/api/v1/user/email-verification
Content-Type: application/json

{
    "otp":"1431128m9",
    "email":"Teter@iii.co"
}
### Get client info
GET http://localhost:8000/api/v1/user
Content-Type: application/json

{
  
}


###### categories


### fetch category
GET http://localhost:8000/api/v1/category
Content-Type: application/json